file_format: "1"
id: comfykey
name: Comfykey
type: shield
url: https://github.com/FrederickAlt/comfykey
requires: [pro_micro]
features:
  - keys
  - display
siblings:
  - comfykey_left
  - comfykey_right
  - comfykey_dongle
